#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const repoRoot = process.cwd();
const quartoPath = path.join(repoRoot, '_quarto.yml');
const reportPath = path.join(repoRoot, 'PLACEHOLDER_CHAPTERS.md');
const jsonPath = path.join(repoRoot, 'placeholder-chapters.json');

let failed = false;
let warned = false;

function fail(msg) {
  console.error(`ERROR: ${msg}`);
  failed = true;
}

function warn(msg) {
  console.warn(`WARN: ${msg}`);
  warned = true;
}

function ok(msg) {
  console.log(`OK: ${msg}`);
}

if (!fs.existsSync(quartoPath)) {
  fail('Missing _quarto.yml');
  process.exit(1);
}

const quarto = fs.readFileSync(quartoPath, 'utf8');
const chapterMatches = [...quarto.matchAll(/-\s+(chapters\/[A-Za-z0-9._\/-]+\.qmd)/g)].map((m) => m[1]);
const uniqueChapters = [...new Set(chapterMatches)];

if (!uniqueChapters.length) {
  fail('No chapter paths found in _quarto.yml');
}

ok(`Found ${uniqueChapters.length} chapter entries in _quarto.yml`);

const templatePhrases = [
  'subtitle: "[Product name TBD]"',
  '## Product: [TBD]',
  '**Date**: [TBD]',
  '**Repo**: [TBD]',
  '*[To be written after we build it]*',
  '*[Real-time narrative goes here]*',
  '*[What we actually delivered]*',
  '*[What I learned]*'
];

const placeholderDayChapters = [];
const missingChapters = [];

for (const rel of uniqueChapters) {
  const full = path.join(repoRoot, rel);
  if (!fs.existsSync(full)) {
    fail(`Referenced chapter missing: ${rel}`);
    missingChapters.push(rel);
    continue;
  }
  ok(`Chapter exists: ${rel}`);

  const text = fs.readFileSync(full, 'utf8');
  const isDayChapter = /chapters\/day-(\d+)\.qmd$/.test(rel);
  if (!isDayChapter) continue;

  const match = rel.match(/chapters\/day-(\d+)\.qmd$/);
  const dayNumber = match ? Number(match[1]) : null;

  const frontmatterMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const frontmatterText = frontmatterMatch ? frontmatterMatch[1] : '';
  const bodyText = frontmatterMatch ? text.slice(frontmatterMatch[0].length) : text;

  const hasPlaceholderFrontmatter = /\[TBD\]/.test(frontmatterText);
  const hasTemplateBody = templatePhrases
    .filter((phrase) => !phrase.startsWith('subtitle:') && !phrase.startsWith('## Product:') && !phrase.startsWith('**Date**:') && !phrase.startsWith('**Repo**:'))
    .some((phrase) => bodyText.includes(phrase));
  const hasTemplateCallout = ['## Product: [TBD]', '**Date**: [TBD]', '**Repo**: [TBD]'].some((phrase) => bodyText.includes(phrase));

  const isPlaceholder = hasPlaceholderFrontmatter || hasTemplateCallout || hasTemplateBody;
  if (isPlaceholder) {
    placeholderDayChapters.push({ path: rel, day: dayNumber });
  }
}

placeholderDayChapters.sort((a, b) => a.day - b.day);
const nextPriority = placeholderDayChapters.slice(0, 5);

const report = [
  '# Placeholder Chapter Audit',
  '',
  'Auto-generated by `node scripts/validate-book.js`.',
  '',
  `- Referenced chapter entries in \`_quarto.yml\`: **${uniqueChapters.length}**`,
  `- Missing referenced chapter files: **${missingChapters.length}**`,
  `- Placeholder day chapters still needing honest rewrites: **${placeholderDayChapters.length}**`,
  ''
];

if (missingChapters.length) {
  report.push('## Missing Referenced Files', '');
  for (const rel of missingChapters) report.push(`- \`${rel}\``);
  report.push('');
}

report.push('## Next Priority Rewrites', '');
if (nextPriority.length) {
  for (const item of nextPriority) report.push(`- Day ${String(item.day).padStart(2, '0')} — \`${item.path}\``);
} else {
  report.push('- None');
}

report.push('', '## Placeholder Day Chapters', '');
if (placeholderDayChapters.length) {
  for (const item of placeholderDayChapters) report.push(`- Day ${String(item.day).padStart(2, '0')} — \`${item.path}\``);
} else {
  report.push('- None');
}
report.push('', '## Notes', '', '- This audit is a manuscript-integrity check, not a render check.', '- `quarto render` is still the publication gate when Quarto is available.', '- Exit code `0` = clean, `1` = broken references, `2` = references resolve but placeholder day chapters remain.', '');

fs.writeFileSync(reportPath, report.join('\n'));
fs.writeFileSync(
  jsonPath,
  JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      chapterCount: uniqueChapters.length,
      missingChapters,
      placeholderDayChapters,
      nextPriority
    },
    null,
    2
  ) + '\n'
);
ok(`Wrote report: ${path.basename(reportPath)}`);
ok(`Wrote report: ${path.basename(jsonPath)}`);

if (placeholderDayChapters.length) {
  warn(`Placeholder day chapters still present (${placeholderDayChapters.length}):`);
  for (const item of placeholderDayChapters) {
    console.warn(`WARN:   - Day ${String(item.day).padStart(2, '0')}: ${item.path}`);
  }
}

if (failed) process.exit(1);
if (warned) process.exit(2);
ok('Book validation passed');
